---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.java
    version: "1.9.6" # note that ranges are not supported for roles

collections:
  # Install a collection from Ansible Galaxy.
  - name: geerlingguy.php_roles
    version: ">=0.9.3"
    # source: https://galaxy.ansible.com

  # Built-in
  - name: community.general
    version: 5.5.0
  - name: ansible.posix
    version: 1.4.0
  - name: ansible.utils
    version: 2.6.1

  # VMware vSphere
  # community.vmware pulls in the vmware.vmware collection.
  #
  # We need it as not all modules are migrated over to the vmware.vmware
  # collection.
  - name: community.vmware
    version: 5.0.1

  # Red Hat
  - name: freeipa.ansible_freeipa
    version: 1.8.4
  - name: redhat.openshift
    version: 3.0.1
    # source: https://console.redhat.com/api/automation-hub/content/published/
  - name: redhat.satellite
    version: 3.7.0
    # source: https://console.redhat.com/api/automation-hub/content/published/
